// aqui ficam os conteúdos permanentes que são renderizados em todas as páginas!

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '../components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark antialiased">
      {/* "dark" segue a definição "class" em darkMode no tw.config. Pode-se criar um botão p/controlar os modos! */}{' '}
      {/* antialiased é a classe do TW que deixa as fontes mais definidas! */}
      <body className={inter.className}>
        <div className="min-h-screen lg:grid lg:grid-cols-app dark:bg-zinc-900">
          <Sidebar />
          <main className="max-w-[100vw] px-4 pb-12 pt-24 lg:col-start-2 lg:px-8 lg:pt-8">
            {children}
          </main>{' '}
          {/* col-start-2 força o main a ocupar a 2º col do grid */}
        </div>
        {/* min-h-screen garante que o conteúdo sempre ocupe pelo menos a altura da tela */}
      </body>
      {/* children representa o conteúdo de cada pág q será renderizada dinamicamente! */}
    </html>
  )
}

// Anotações:
// No TW, o "_" deve ser colocado no lugar do espaço em branco. Ex: bg-slate-50
