// aqui ficam os conteúdos permanentes que são renderizados em todas as páginas!

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid-cols-app grid min-h-screen">
          <aside className="border-r border-zinc-200 px-5 py-8">sidebar</aside>
          <main className="px-4 pb-12 pt-8">{children}</main>
        </div>
        {/* min-h-screen garante que o conteúdo sempre ocupe pelo menos a altura da tela */}
      </body>
      {/* children representa o conteúdo de cada pág q será renderizada dinamicamente! */}
    </html>
  )
}

// Anotações:
// No TW, o "_" deve ser colocado no lugar do espaço em branco. Ex: bg-slate-50
